# Install script for directory: D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/examples

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/OpenSceneGraph")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osg2cpp/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganalysis/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganimate/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgatomiccounter/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgautocapture/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgautotransform/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgbillboard/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgblenddrawbuffers/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgblendequation/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgcallback/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgcamera/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgcatch/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgclip/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgcompositeviewer/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgcopy/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgcubemap/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgdelaunay/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgcluster/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgdatabaserevisions/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgdepthpartition/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgdepthpeeling/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgdrawinstanced/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgdistortion/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgfadetext/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgfont/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgforest/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgfxbrowser/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgoutline/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osggameoflife/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osggeometry/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osggeometryshaders/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osghangglide/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osghud/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgimagesequence/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgimpostor/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgintersection/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgkdtree/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgkeyboard/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgkeyboardmouse/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgkeystone/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osglauncher/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osglight/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osglightpoint/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osglogicop/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osglogo/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osggpucull/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osggpx/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osggraphicscost/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgmanipulator/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgmovie/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgmultiplemovies/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgmultiplerendertargets/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgmultitexture/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgmultitexturecontrol/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgmultitouch/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgmultiviewpaging/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgoccluder/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgocclusionquery/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgoit/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgoscdevice/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgpackeddepthstencil/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgpagedlod/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgparametric/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgparticle/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgparticleeffects/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgparticleshader/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgpick/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgplanets/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgpoints/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgpointsprite/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgposter/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgprecipitation/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgprerender/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgprerendercubemap/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgreflect/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgrobot/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgSSBO/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgscalarbar/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgscribe/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgsequence/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgshaders/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgshadercomposition/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgshadergen/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgshaderterrain/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgshadow/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgshape/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgsharedarray/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgsimpleshaders/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgsimplifier/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgsimulation/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgsidebyside/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgslice/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgspacewarp/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgspheresegment/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgspotlight/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgstereoimage/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgstereomatch/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgterrain/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgthreadedterrain/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtransferfunction/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtext/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtext3D/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtexture1D/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtexture2D/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtexture2DArray/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtexture3D/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtexturerectangle/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtexturecompression/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgthirdpersonview/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtransformfeedback/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osguniformbuffer/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osguserstats/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgvertexprogram/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgvertexattributes/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgvolume/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwindows/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgvirtualprogram/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganimationhardware/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganimationtimeline/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganimationnode/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganimationmakepath/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganimationmorph/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganimationskinning/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganimationsolid/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganimationviewer/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osganimationeasemotion/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetaddremove/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetbox/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetcanvas/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetframe/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetinput/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetlabel/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetmessagebox/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetmenu/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetnotebook/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetperformance/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetscrolled/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetshader/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetstyled/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgettable/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgwidgetwindow/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osguserdata/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgsimplegl3/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgunittests/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgmemorytest/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgfpdepth/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgscreencapture/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgmotionblur/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgteapot/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgphotoalbum/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtessellate/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgtessellationshaders/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgcomputeshaders/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgpdf/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgviewerGLUT/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgviewerQt/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgqfont/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgQtWidgets/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgQtBrowser/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgviewerFLTK/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/examples/osgviewerMFC/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

