# Install script for directory: D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/src/osgPlugins

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/OpenSceneGraph")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/osga/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/rot/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/scale/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/trans/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/normals/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/revisions/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/view/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/shadow/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/terrain/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/osg/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/ive/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/cfg/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/glsl/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/rgb/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/bmp/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/pnm/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/dds/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/tga/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/hdr/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/dot/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/vtf/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/ktx/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/jpeg/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/jp2/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/exr/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/gif/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/png/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/tiff/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/gdal/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/ogr/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/dicom/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/3dc/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/p3d/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/curl/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/gz/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/dae/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/fbx/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/dw/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/bvh/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/x/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/dxf/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/OpenFlight/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/obj/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/pic/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/stl/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/3ds/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/ac/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/pov/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/logo/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/lws/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/md2/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/osgtgz/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/tgz/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/shp/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/txf/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/bsp/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/mdl/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/gles/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/osgjs/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/lwo/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/ply/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/txp/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/nvtt/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/freetype/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/qfont/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/zip/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/pvr/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/osc/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/trk/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/tf/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/las/cmake_install.cmake")
  INCLUDE("D:/Development/op3d_active/OpenSceneGraph-3.4.0-rc5/msvc/src/osgPlugins/lua/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

